### ISSUE TITLE
Under load, js-csp doesn't have sufficient buffer space

### ISSUE THREAD

**Issue by daviddawson** [muoncore/muon-node#30]
Muon Version: 7.1.7
Language: javascript

Services in Use: Gateway

muon js gateway will periodically fail with this error

391b6-4b83-4e67-87f4-41dc85fa1fb9","67031d04-27ad-4397-8d71-d54031adefbe"]
gateway_1        | Sat, 19 Nov 2016 15:42:12 GMT [info] in transport-client.js:32 Virtual channels are ["258abd19-dd4d-46da-9983-c3962572e1de","8833f987-a705-48c2-a4ee-27f2b38dc292","aebbabb5-4c39-4dd4-a2c9-0e49cac61b6a","e80f7cef-8adf-481b-88ee-d709aecc17bf"]
gateway_1        | Sat, 19 Nov 2016 15:42:12 GMT [info] in transport-client.js:32 Virtual channels are ["d06ffef5-4530-4a17-bfaf-bf15bfac1d3d","b397e676-e7c5-4af0-8c3a-ab1f04b0a45a"]
gateway_1        | /applocal/node_modules/js-csp/lib/impl/channels.js:118
gateway_1        |       throw new Error("No more than " + MAX_QUEUE_SIZE + " pending puts are allowed on a single channel.");
gateway_1        |       ^
gateway_1        | 
gateway_1        | Error: No more than 1024 pending puts are allowed on a single channel.
gateway_1        |     at Channel._put (/applocal/node_modules/js-csp/lib/impl/channels.js:118:13)
gateway_1        |     at Object.put_then_callback [as putAsync] (/applocal/node_modules/js-csp/lib/impl/process.js:27:24)
gateway_1        |     at Object.send (/applocal/node_modules/muon-core/muon/infrastructure/channel.js:80:30)
gateway_1        |     at /applocal/node_modules/muon-core/muon/transport/amqp/transport.js:70:20
gateway_1        |     at /applocal/node_modules/muon-core/muon/infrastructure/channel.js:212:25
gateway_1        |     at next (native)
gateway_1        |     at Process.run (/applocal/node_modules/js-csp/lib/impl/process.js:87:23)
gateway_1        |     at /applocal/node_modules/js-csp/lib/impl/process.js:63:10
gateway_1        |     at Immediate.process_messages (/applocal/node_modules/js-csp/lib/impl/dispatch.js:42:5)
gateway_1        |     at runCallback (timers.js:628:20)
gateway_1        | 
gateway_1        | npm info lifecycle corgi-email@0.1.0~start: Failed to exec start script
gateway_1        | npm ERR! Linux 4.4.0-47-generic
gateway_1        | npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
gateway_1        | npm ERR! node v6.8.0
gateway_1        | npm ERR! npm  v3.10.8
gateway_1        | npm ERR! code ELIFECYCLE
gateway_1        | npm ERR! corgi-email@0.1.0 start: `node gateway.js`

**Comment by daviddawson** [comment]
This also affects the http proxy.     Potentially a resource leak.

Might be in shared channel usage, as when the proxy crashed, it had been reporting that a shared channel was kept open, for a very long time with no traffic, which seems incorrect.
